name: soltec_academy
description: A mobile application for Soltec Academy student.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  # firebase_auth: ^4.13.0
  # cloud_firestore:
  # firebase_storage: ^11.5.0
  # firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
