// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErjVtc-UtrXjH5J-74IvOLisBtOgPAUU',
    appId: '1:462531094119:web:98e9ff7569d8192c7f56c2',
    messagingSenderId: '462531094119',
    projectId: 'soltec-academy',
    authDomain: 'soltec-academy.firebaseapp.com',
    storageBucket: 'soltec-academy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFyisFuwK-lznv_5QQAAdlmDj4H5MivU',
    appId: '1:462531094119:android:29bf5dbf8e1c35f47f56c2',
    messagingSenderId: '462531094119',
    projectId: 'soltec-academy',
    storageBucket: 'soltec-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtZfnalYNBUTh7cJaS2EijaRTz9xpsXCk',
    appId: '1:462531094119:ios:95229f2120ab71757f56c2',
    messagingSenderId: '462531094119',
    projectId: 'soltec-academy',
    storageBucket: 'soltec-academy.appspot.com',
    iosBundleId: 'com.example.soltecAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtZfnalYNBUTh7cJaS2EijaRTz9xpsXCk',
    appId: '1:462531094119:ios:798ccf8af391c07f7f56c2',
    messagingSenderId: '462531094119',
    projectId: 'soltec-academy',
    storageBucket: 'soltec-academy.appspot.com',
    iosBundleId: 'com.example.soltecAcademy.RunnerTests',
  );
}
